# Generated by Django 3.2 on 2021-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newaccount', '0002_auto_20210501_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='userAadhaarImage',
            field=models.ImageField(default=0.0, upload_to='aadhaar/'),
            preserve_default=False,
        ),
    ]
