# Generated by Django 3.2 on 2021-05-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newaccount', '0003_newuser_useraadhaarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='userRemarks',
            field=models.CharField(default=0.0, max_length=260),
            preserve_default=False,
        ),
    ]
