# Generated by Django 3.2 on 2021-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newaccount', '0004_newuser_userremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='tc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='userGender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
    ]
